/**
 * infra/ — LAYER: implementations of domain ports. Cannot import features/ or ui/.
 *
 * Public API barrel. Import this layer only through its index (`eslint-plugin-boundaries`).
 * Dependency rule (§M3): UI → Feature → Domain → Infra. Never the reverse.
 */
export {
  queryClient,
  api,
  refreshAccessToken,
  warmBackend,
  sendChatMessage,
  fetchMessagesAfter,
  normalizeSendAck,
  normalizeServerMessage,
  createDm,
  getConversationDetails,
  getConversationMembers,
  getPresence,
  subscribePresence,
  normalizePresenceEvent,
  AppError,
  isAppError,
  normalizeError,
  getAccessToken,
  getRefreshToken,
  getDeviceId,
  getAccountId,
  getPhone,
  hasSession,
  setTokens,
  clearSession,
  getOprfKey,
  oprfEvaluate,
  oprfRegister,
  oprfMatch,
  OPRF_EVALUATE_BATCH_CAP,
  OPRF_MATCH_BATCH_CAP,
} from './network';
export type {
  AppErrorKind,
  SessionTokens,
  SendMessageInput,
  SendAck,
  ServerMessage,
  CreateDmResult,
  ConversationDetails,
  ConversationType,
  OprfKeyResponse,
  OprfEvaluateResponse,
} from './network';
export { storage, kv, KVKeys, useKVString } from './kv';
export {
  Conversation,
  Message,
  observeConversations,
  listConversationIds,
  clearUnread,
  upsertConversation,
  purgeAllLocalChat,
  observeMessages,
  sendMessageLocal,
  applyServerMessage,
  applyServerMessages,
  markMessageSent,
  markMessageFailed,
  markMessageSending,
  maxSeqForConversation,
  applyReceipt,
  enqueueSend,
  claimNextDue,
  markAckd,
  markFailed,
  recoverStuckSends,
  requeueFailed,
  outboxStats,
  reconcileDecision,
  backoffMs,
  nextOutboxRetry,
  MAX_SEND_ATTEMPTS,
  searchConversations,
  searchMessages,
  fetchConversationNames,
  sanitizeLikeQuery,
} from './db';
export type {
  OutboxItem,
  OutboxStats,
  ReconcileAction,
  BackoffOptions,
  ConversationPatch,
  ConversationSearchHit,
  MessageSearchHit,
} from './db';
export { RealtimeSocket, WS_CODE_DEAD, WS_CODE_UNAUTHORIZED } from './realtime';
export type { RealtimeSocketCallbacks } from './realtime';
export {
  ensureDeviceKey,
  signChallenge,
  hasDeviceKey,
  clearDeviceKey,
  bytesToBase64,
  base64ToBytes,
  hashToBigInt,
  blind,
  unblind,
  mgf1,
  parseOprfPublicKey,
  modPow,
  modInverse,
  bytesToBigInt,
  bigIntToBytes,
  bigIntToBase64Url,
  base64UrlToBigInt,
  randomBigIntBelow,
} from './crypto';
export type { OprfPublicKey, BlindResult } from './crypto';
export {
  getBatteryStatus,
  getNetworkStatus,
  subscribeNetwork,
  requestNotificationPermission,
  hasNotificationPermission,
  hapticTick,
  hapticSelection,
  requestCameraPermission,
  requestMicrophonePermission,
  requestContactsPermission,
  requestBluetoothPermission,
  ensureContactsPermission,
  checkContactsPermission,
  readDeviceContacts,
} from './native';
export type {
  BatteryStatus,
  NetworkStatus,
  NotificationPermission,
  DeviceContact,
  ContactsAccess,
} from './native';
export { toE164, regionFromE164 } from './util';
