/**
 * infra/ — LAYER: implementations of domain ports. Cannot import features/ or ui/.
 *
 * Public API barrel. Import this layer only through its index (`eslint-plugin-boundaries`).
 * Dependency rule (§M3): UI → Feature → Domain → Infra. Never the reverse.
 */
export {
  queryClient,
  api,
  refreshAccessToken,
  refreshSession,
  warmBackend,
  sendChatMessage,
  fetchMessagesAfter,
  fetchPeerReceipts,
  normalizeSendAck,
  normalizeServerMessage,
  createDm,
  getConversationDetails,
  getConversationMembers,
  fetchInbox,
  getPresence,
  subscribePresence,
  presenceOnline,
  presenceOffline,
  presenceHeartbeat,
  PRESENCE_ONLINE_TTL_MS,
  normalizePresenceEvent,
  AppError,
  isAppError,
  normalizeError,
  getAccessToken,
  getRefreshToken,
  getDeviceId,
  getAccountId,
  getPhone,
  hasSession,
  hasValidSession,
  accessTokenExpiresInMs,
  setTokens,
  clearSession,
  subscribeSession,
  getOprfKey,
  oprfEvaluate,
  oprfRegister,
  oprfMatch,
  oprfRegisterEdges,
  OPRF_EVALUATE_BATCH_CAP,
  OPRF_MATCH_BATCH_CAP,
} from './network';
export type {
  AppErrorKind,
  SessionTokens,
  SendMessageInput,
  SendAck,
  ServerMessage,
  CreateDmResult,
  ConversationDetails,
  InboxConversation,
  ConversationType,
  OprfKeyResponse,
  OprfEvaluateResponse,
} from './network';
export { storage, kv, KVKeys, useKVString } from './kv';
export {
  Conversation,
  Message,
  observeConversations,
  listConversationIds,
  clearUnread,
  upsertConversation,
  peerIdentityAgeMs,
  conversationIdsForPeer,
  peerIdFor,
  observeConversation,
  purgeAllLocalChat,
  observeMessages,
  sendMessageLocal,
  applyServerMessage,
  applyServerMessages,
  markMessageSent,
  markMessageFailed,
  markMessageSending,
  maxSeqForConversation,
  countMessagesWithSeq,
  maxContiguousSeqForConversation,
  minSeqForConversation,
  countMessages,
  MESSAGE_PAGE,
  applyReceipt,
  enqueueSend,
  enqueueOptimisticSend,
  claimNextDue,
  markAckd,
  markFailed,
  recoverStuckSends,
  requeueFailed,
  outboxStats,
  reconcileDecision,
  classifySendFailure,
  shouldProbeGap,
  backoffMs,
  searchConversations,
  searchMessages,
  fetchConversationNames,
  sanitizeLikeQuery,
  pendingReceiptFrames,
  parseReceiptFrame,
  dmConversationId,
  mergeWatermark,
  EMPTY_WATERMARKS,
  getDesired,
  getSent,
  noteDesired,
  noteSent,
  getPeerWatermark,
  notePeerWatermark,
  markDirty,
  takeDirty,
  hasDirty,
  reassertReceipts,
  clearAllReceipts,
} from './db';
export type {
  OutboxItem,
  OutboxStats,
  ReconcileAction,
  BackoffOptions,
  ConversationPatch,
  RowStream,
  ConversationSearchHit,
  MessageSearchHit,
} from './db';
export { RealtimeSocket, WS_CODE_DEAD, WS_CODE_UNAUTHORIZED } from './realtime';
export type { RealtimeSocketCallbacks } from './realtime';
export {
  ensureDeviceKey,
  signChallenge,
  hasDeviceKey,
  clearDeviceKey,
  bytesToBase64,
  base64ToBytes,
  hashToBigInt,
  blind,
  unblind,
  mgf1,
  parseOprfPublicKey,
  modPow,
  modInverse,
  bytesToBigInt,
  bigIntToBytes,
  bigIntToBase64Url,
  base64UrlToBigInt,
  randomBigIntBelow,
  batchModInverse,
  unblindBatch,
} from './crypto';
export type { OprfPublicKey, BlindResult } from './crypto';
export {
  getBatteryStatus,
  getNetworkStatus,
  subscribeNetwork,
  requestNotificationPermission,
  hasNotificationPermission,
  hapticTick,
  hapticSelection,
  requestCameraPermission,
  requestMicrophonePermission,
  requestContactsPermission,
  requestBluetoothPermission,
  ensureContactsPermission,
  checkContactsPermission,
  readDeviceContacts,
  getAppState,
  subscribeAppState,
} from './native';
export type {
  BatteryStatus,
  NetworkStatus,
  NotificationPermission,
  DeviceContact,
  ContactsAccess,
  AppStateStatus,
} from './native';
export {
  initPush,
  unregisterPush,
  disposePush,
  getPushStatus,
  subscribePushAvailability,
  subscribePushMessages,
  subscribePushEvents,
  drainPendingEvents,
  takeQueuedPushEvents,
  syncConversationNames,
  syncPersonNames,
  syncPersonAvatars,
  setNativeMute,
  setNativeSafeReadSeq,
  clearConversationNotification,
  setActiveConversationForPush,
  getPushBlocker,
  resolvePushBlocker,
} from './push';
export type { PushBlocker } from './push';
export type {
  PushMessage,
  PushPendingEvent,
  PushPermission,
  PushPhase,
  PushStatus,
} from './push';
export { toE164, regionFromE164, yieldToEventLoop, mapYielding } from './util';
