/**
 * Which origins a launch-time wake-up request is worth sending to (VC-008).
 *
 * Pure on purpose. The fetch this feeds is fire-and-forget: it discards the response, swallows
 * every error and is never awaited, so nothing downstream can observe whether it did the right
 * thing. The decision therefore has to be testable on its own, or it is not checkable at all —
 * which is how it spent a release aiming requests at services it could not wake.
 *
 * WHAT IS BEING WOKEN, AND WHERE. Render's free tier sleeps a service after ~15 min idle and
 * charges the next caller 30-50s to wake it (VC-008 measured 36s for the edge gateway, 43s for
 * realtime) — long enough to lose the request to the 60s axios timeout, and it lands on the
 * user's first tap. That is the only condition this module exists for, and it holds in exactly
 * one of the deployments the app can be built against:
 *
 *   dev   `axis6` on Render — six services behind an edge gateway, free tier, sleeps. Warmable.
 *   prod  `mono` on the Azure VM behind Caddy — ONE process, every feature group inside it, up
 *         for as long as the VM is up. Nothing hibernates; the only outage is the VM's 19:30 IST
 *         auto-shutdown, and no HTTPS GET can start a deallocated VM. Not warmable.
 *   local `pnpm reverse` / the emulator's host alias — a process the developer started.
 *
 * That topology was genuinely contested in the repo: `docs/backend-integration-reference.md`
 * §3/§8 calls production "per-service on Render, NOT single-origin", `.env.prod` calls it one
 * Azure origin. `D:\Velchat\docs\RUNBOOK.md` §0b settles it in favour of the env file — it is
 * the source both env files cite and `src/core/config/env.ts` already quotes — and the
 * integration reference is simply older than the decision, which it flags as unconfirmed at the
 * time of writing. So the per-service fan-out VC-008 asked for was only ever a DEV concern.
 *
 * WHY IT STILL WILL NOT FAN OUT ACROSS THE SIX DEV SERVICES. Not because the hostnames are
 * unknown any more: RUNBOOK §0b lists all six, and VC-007's session got 200 from five of them
 * directly. Because of what shipping them would cost.
 *   - That same paragraph says the `-2aje` suffix is generated by Render when a name collides,
 *     is resolved between services with `fromService`, and is "never hardcoded anywhere — do not
 *     copy it into config". A service recreated under a new suffix turns a baked list into five
 *     launch requests aimed at whoever holds those names next.
 *   - `android/app/src/main/res/xml/network_security_config.xml` holds one `<domain-config>` per
 *     `.env.*` origin, and `infra/native/__tests__/transportSecurity.test.ts` reads both real
 *     files to assert that nothing is missing — because a host the XML does not name is silently
 *     UNPINNED, indistinguishable at runtime from a pinned one. Reaching a sixth host from here
 *     would open exactly that hole, in the control that was just built to close it.
 * So the rule is structural rather than a judgement call: the warm-up may only ever contact an
 * origin `appEnv` already names, which is the same set the pinning config is kept in step with.
 */
import { endpointHost } from '../native/transportSecurity';

/**
 * The endpoints of the flavor this binary was built with.
 *
 * Deliberately NOT `AppEnv`: the decision must not be able to read `appEnv.name`. VC-035 was a
 * build whose `Config` came back empty and reported itself as `dev` while pointing at
 * production, and the lesson was that the URL is the thing that is true. Where a request goes is
 * decided by the URL it is going to, never by what the build calls itself.
 */
export interface WarmupOrigins {
  readonly apiBaseUrl: string;
  readonly wsUrl: string;
}

/**
 * The one hosting platform in this repo's config that sleeps its instances. This is a PLATFORM
 * suffix read off the origins already in `.env.*`, not a service hostname — it adds no host to
 * the set the app can talk to, it only narrows that set to the members a wake request can help.
 */
const HIBERNATING_PLATFORM = 'onrender.com';

/**
 * Matched at a label boundary, never as a substring. `onrender.com.example.test` is a host
 * somebody else controls, and a substring test would have this module sending launch traffic to
 * it on the strength of a coincidence.
 */
function hibernates(host: string): boolean {
  return (
    host === HIBERNATING_PLATFORM || host.endsWith(`.${HIBERNATING_PLATFORM}`)
  );
}

/**
 * The `/health` URL for an endpoint's origin, or `undefined` when the endpoint is not a URL.
 *
 * `/health` and nothing else. The route the old list called "auth-service (login path)" —
 * `/.well-known/jwks.json` — is proxied by the gateway to identity (backend-integration-reference
 * §2) and answers 502 on the dev deployment without the upstream being reached at all (VC-007,
 * measured), so it warmed nothing the line above it had not already warmed. Its only real effect
 * was to make the warm-up read, to a reviewer, as if it covered the login path.
 *
 * The port is part of the origin and is kept; the scheme is normalised (`wss:`→`https:`) because
 * the WS endpoint names a host to be woken, not a socket to be opened. The host is lower-cased
 * so that two spellings of one origin dedupe into one request rather than two.
 */
function healthUrl(endpoint: string): string | undefined {
  const match = /^(https?|wss?):\/\/([^/?#]+)/i.exec(endpoint.trim());
  const scheme = match?.[1]?.toLowerCase();
  const authority = match?.[2];
  if (scheme === undefined || authority === undefined) return undefined;
  // Drop any `user:pass@` — credentials are not part of the origin being woken.
  const origin = authority.slice(authority.lastIndexOf('@') + 1).toLowerCase();
  if (origin === '') return undefined;
  const secure = scheme === 'https' || scheme === 'wss';
  return `${secure ? 'https' : 'http'}://${origin}/health`;
}

/**
 * The health URLs worth pinging at launch — usually none.
 *
 * An empty list is the expected answer for a production build and for the local dev loop, and it
 * is the point: this runs on the cold-start path of a 3 GB Android 10 device (§R4/§R5/§R6), so a
 * request that cannot wake anything is battery and launch time spent for nothing.
 */
export function warmTargets(env: WarmupOrigins): readonly string[] {
  const targets: string[] = [];
  for (const endpoint of [env.apiBaseUrl, env.wsUrl]) {
    // `endpointHost` rather than a second parser: it is the one the pinning config is checked
    // with, so the warm-up and the transport-security policy can never disagree about which host
    // a URL names. It refuses to invent a host out of a non-URL, which is the behaviour wanted
    // here too — a value that is not an origin is dropped, never guessed at.
    const host = endpointHost(endpoint);
    if (host === undefined || !hibernates(host)) continue;
    const url = healthUrl(endpoint);
    // Two endpoints on one origin (prod shares REST and WS; a dev flavor could too) are one
    // sleeping instance and get one request.
    if (url === undefined || targets.includes(url)) continue;
    targets.push(url);
  }
  return targets;
}
